<?php

function dosomething_projects_views_pre_view(&$view) {

  if ($view->name == 'projects_search') {

    /* parse arguments */
    $require_photo = (arg(1) != 'photo') ? FALSE : TRUE;
    $require_video = (arg(2) != 'video') ? FALSE : TRUE;
    $search_term = (arg(3)) ? arg(3) : FALSE;

    if ($require_photo) {
      dpm('requiring photo...');
      $view->display['default']->handler->options['filters']['require_photo'] = array (
        'operator' => 'not empty',
        'value' => array(
          'value' => '',
          'min' => '',
          'max' => '',
          ),
        'group' => '0',
        'exposed' => FALSE,
        'expose' => array(
          'operator' => FALSE,
          'label' => '',
          ),
        'id' => 'delta',
        'table' => 'node_data_field_project_photo',
        'field' => 'delta',
        'override' => array(
          'button' => 'Override',
          ),
        'relationship' => 'none',
      );
    }

    if ($require_video) {
      dpm('requiring video...');
      $view->display['default']->handler->options['filters']['require_video'] = array (
        'operator' => '!=',
        'value' => '',
        'group' => '0',
        'exposed' => FALSE,
        'expose' => array(
          'operator' => FALSE,
          'label' => '',
          ),
        'case' => 1,
        'id' => 'field_embedded_video_provider',
        'table' => 'node_data_field_embedded_video',
        'field' => 'field_embedded_video_provider',
        'override' => array(
          'button' => 'Override',
          ),
        'relationship' => 'none',
      );
    }

    if ($search_term) {
      dpm('requiring term: ' . arg(3) . '...');
      $view->display['default']->handler->options['filters']['search_term'] = array (
        'operator' => 'optional',
        'value' => 'baseball',
        'group' => '0',
        'exposed' => FALSE,
        'expose' => array(
          'operator' => '',
          'label' => '',
        ),
        'id' => 'keys',
        'table' => 'search_index',
        'field' => 'word',
        'relationship' => 'none',
      );
    }

  }
}

?>
