<?php

function dosomething_wf_modify_webform_submission_insert($node, $submission) {
  /*
   * Staples 2011 Sweepstakes submission
   */
  if ($node->nid == 650379) {
    $map = _dosomething_wf_modify_webform_component_mapping($node);
    
    if ($submission->data[$map['share']]['value'][0] != '')
    {
      $node = new StdClass();
      $node->type = 'staples_reason';
      $node->created = time();
      $node->changed = $node->created;
      $node->status = 1;
      $node->promote = 0;
      $node->sticky = 0;
      $node->uid = 1;
      $node->title = $submission->data[$map['share']]['value'][0];
      
      $node->field_name_f[0]['value'] = $submission->data[$map['first_name']]['value'][0];
      $node->field_name_l[0]['value'] = $submission->data[$map['last_name']]['value'][0];
      $node->field_thirteen[0]['value'] = 'yes';
      $node->customGenerated = true;
      node_save($node);
    }
  }
/* Grandparents 2011 -> 2012 */  
 else if ($node->nid == 679707) {
    $map = _dosomething_wf_modify_webform_component_mapping($node);
    $checks = $submission->data[$map['check_boxes']]['value'];
    if (in_array('text', $checks)) {
      ds_mobile_mcommons_optin_campaign($submission->data[$map['phone']]['value'][0], 68611, 79611);
    }
/* END - Grandparents 2011 */	
    if (in_array('email', $checks)) {
        dia_signup(array(
                       'link' => 'groups',
                       'table' => 'supporter',
                       'linkKey' => 105245,
                       'First_Name' => $submission->data[$map['first_name']][0]['value'],
                       'Last_Name' => $submission->data[$map['last_name']][0]['value'],
                       'Email' => $submission->data[$map['email']][0]['value'],
                       'Phone' => $submission->data[$map['phone']][0]['value'],
                       'Zip' => $submission->data[$map['zip']][0]['value']
                     ));
    }
    if (in_array('action_kit', $checks)) {
        $node->webform['redirect_url'] = 'sports/action-kit';
    }
 }
  /*Give a Spit About cancer webform*/
 else if ($node->nid == 682753) {
   $map = _dosomething_wf_modify_webform_component_mapping($node);
   ds_mobile_mcommons_optin_campaign($submission->data[$map['phone']]['value'][0], 67751, 82281);
 }
  /*Give a Spit - Join this Drive webform on Schools Page*/

 else if ($node->nid == 704188) {
      $map = _dosomething_wf_modify_webform_component_mapping($node);
          ds_mobile_mcommons_optin_campaign($submission->data[$map['phone']]['value'][0], 67751, 82281);
 }
 
 
 /*Teens for Jeans Splash*/
 else if ($node->nid == 720997) {
 	 $map = _dosomething_wf_modify_webform_component_mapping($node);
	 
	// send the email to infusionsoft
	include 'isdk.php';
	$app = new iSDK;

	if($app->cfgCon("emaildrop")) {
		// set up the data to send to infusionsoft
		$contact=array('Email' => $submission->data[$map['email']]['value'][0]);
		// apply the Teens for jeans tags
		$actionId = 748;
		//check for existing contact;
		$returnFields = array('Id');
		$dups = $app->findByEmail($contact['Email'], $returnFields);
		/*If email is not a duplicate*/
		if (empty($dups)) {
			// add new contact and add them to the action set
			$dups = $app->addCon($contact);	
			$app->runAS($dups, $actionId);
		} 
		else
		{
			/*If the email is a duplicate*/
			$contactId = $dups[0][Id];
			$app->runAS($contactId, $actionId);
		}
	}
  ds_mobile_mcommons_optin_campaign($submission->data[$map['phone_number']]['value'][0], 74002, 89072);
 }
 else if ($node->nid == 722522) { 
	 $map = _dosomething_wf_modify_webform_component_mapping($node);	 
	// send the email to infusionsoft
	include 'isdk.php';
	$app = new iSDK;

	if($app->cfgCon("emaildrop")) {

		// set up the data to send to infusionsoft
		$contact=array('Email' => $submission->data[$map['email']]['value'][0]);
		
		// apply the Teens for jeans tags
		/* grandparents gone wired */
		$actionId = 852;

		//check for existing contact;
		$returnFields = array('Id');
		$dups = $app->findByEmail($contact['Email'], $returnFields);
		
		/*If email is not a duplicate*/
		if (empty($dups)) {
			// add new contact and add them to the action set
			$dups = $app->addCon($contact);	
			$app->runAS($dups, $actionId);
		} 
		else
		{
			/*If the email is a duplicate*/
			/*
			
			$groupId = 734;
			$result = $app->grpAssign($contactId, $groupId);			
			*/
			$contactId = $dups[0][Id];
			$app->runAS($contactId, $actionId);
		}
	}
 } 
 
 /*College Survey webform*/
 else if ($node->nid == 726972) { 
	 $map = _dosomething_wf_modify_webform_component_mapping($node);
	/*Infusionsoft Library*/
	include 'isdk.php';
	$app = new iSDK;

	if($app->cfgCon("emaildrop")) {
		// set up the data to send to infusionsoft
		$contact=array('Email' => $submission->data[$map['email']]['value'][0]);		
		// apply the College Survey tag
		$actionId = 868;
		//check for existing contact;
		$returnFields = array('Id');
		$dups = $app->findByEmail($contact['Email'], $returnFields);
		
		/*If email is not a duplicate*/
		if (empty($dups)) {
			// add new contact and add them to the action set
			$dups = $app->addCon($contact);	
			$app->runAS($dups, $actionId);
		} 
		else
		{
			/*If the email is a duplicate*/			
			$contactId = $dups[0][Id];
			$app->runAS($contactId, $actionId);
		}
	}
 } 
 else if ($node->nid == 731708) {
   $map = _dosomething_wf_modify_webform_component_mapping($node);
   dosomething_functions_infusionsoft(932, $submission->data[$map['enter_your_email_address']]['value'][0]);
 }
 else if ($node->nid == 736100) {
  global $user;
  $map = _dosomething_wf_modify_webform_component_mapping($node);
  $gsid = $submission->data[$map['gsid']]['value'][0];
  $query = "SELECT nid FROM {content_type_school} WHERE field_gsid_value = $gsid";
  $rs = db_query($query);
  if (mysql_num_rows($rs) == 0) {
    $school = new StdClass();
    $school->type = 'school';
    $school->status = 1;
    $school->uid = $user->uid;
    $school->title = $submission->data[$map['name_of_school']]['value'][0];
    $school->field_state[0]['value'] = $submission->data[15]['value'][0];
    $school->field_gsid[0]['value'] = $gsid;
    if ($school = node_submit($school)) {
      node_save($school);
    }
  }
  else {
    $school = node_load(db_fetch_object($rs)->nid);
  }
  og_save_subscription($school->nid, $user->uid, array('is_active' => 1));
  $friends = array();
  for ($i = 1; $i <= 5; $i++) {
    if (!empty($submission->data[$map['friend_email_'.$i]]['value'][0]))
      $friends[] = $submission->data[$map['friend_email_'.$i]]['value'][0];
  }
  dosomething_functions_infusionsoft(1096, $friends);
  if ((isset($map['opt_in']) && $submission->data[$map['opt_in']]['value'][0] == 'yes') || !isset($map['opt_in'])) {
    dosomething_functions_infusionsoft(1036, $submission->data[$map['email']]['value'][0]);
    ds_mobile_mcommons_optin_campaign($submission->data[$map['phone_number']]['value'][0], 13751, 97351);
  }
 }
  

 /* HIV aka. Update Your Status */  
 else if ($node->nid == 734426 || $node->nid == 736130) {
   $map = _dosomething_wf_modify_webform_component_mapping($node);
   dosomething_functions_infusionsoft(1024, $submission->data[$map['email']]['value'][0]);
   ds_mobile_mcommons_optin_campaign($submission->data[$map['phone_number']]['value'][0], 78971, 95641);
 }
 
 /* Green Your School */
 else if ($node->nid == 735506 || $node->nid == 736100) {
  $map = _dosomething_wf_modify_webform_component_mapping($node);
  if ((isset($map['opt_in']) && $submission->data[$map['opt_in']]['value'][0] == 'yes') || !isset($map['opt_in'])) {
   dosomething_functions_infusionsoft(1036, $submission->data[$map['email']]['value'][0]);
   ds_mobile_mcommons_optin_campaign($submission->data[$map['phone_number']]['value'][0], 13751, 97351);
  }
 }

 /* Battle for the Bands 2012 */ 

 else if ($node->nid == 737134) {
  $map = _dosomething_wf_modify_webform_component_mapping($node);
  $phone = $submission->data[$map['phone_number']]['value'][0];

  if ((isset($map['opt_in']) && $submission->data[$map['opt_in']]['value'][0] == 'yes') || !isset($map['opt_in'])) {
    ds_mobile_mcommons_optin_campaign($phone, 53191, 95791);
    dosomething_functions_infusionsoft(1050, $submission->data[$map['email']]['value'][0]);
  }
  //GET FRIENDS
  ds_mobile_mcommons_optin_campaign($submission->data[$map['cell_number_'.$i]]['value'][0], 53191, 95851);
  $update_url = 'http://dosomething.mcommons.com/profiles/join';
  $fields = 'person[phone]='.urlencode($phone)
    .'&friends[]='.$submission->data[$map['cell_number_1']]['value'][0]
    .'&friends[]='.$submission->data[$map['cell_number_2']]['value'][0]
    .'&friends[]='.$submission->data[$map['cell_number_3']]['value'][0]
    .'&friends[]='.$submission->data[$map['cell_number_4']]['value'][0]
    .'&friends[]='.$submission->data[$map['cell_number_5']]['value'][0]
    .'&opt_in_path=95791&friends_opt_in_path=95851';

  $ch = curl_init();
  curl_setopt($ch,CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch,CURLOPT_URL,$update_url);
  curl_setopt($ch,CURLOPT_POST,count($fields));
  curl_setopt($ch,CURLOPT_POSTFIELDS,$fields);
  $result = curl_exec($ch);
  curl_close($ch);
 }
 else if ($node->nid == 737152) {
   $map = _dosomething_wf_modify_webform_component_mapping($node);
   if ((isset($map['opt_in']) && $submission->data[$map['opt_in']]['value'][0] == 'yes') || !isset($map['opt_in'])) {
     dosomething_functions_infusionsoft(1050, $submission->data[$map['email']]['value'][0]);
     ds_mobile_mcommons_optin_campaign($submission->data[$map['phone_number']]['value'][0], 53191, 58751);
   }
 }

  /*
 else if ($node->nid == ***WEBFORM_NID***) {
   $map = _dosomething_wf_modify_webform_component_mapping($node);
   dosomething_functions_infusionsoft(***ACTION_ID***, $submission->data[$map['***EMAIL_KEY***']]['value'][0]);
   ds_mobile_mcommons_optin_campaign($submission->data[$map['***PHONE_KEY***']]['value'][0], ***CAMPAIGN_ID***, ***OPT_IN_PATH_ID***);
 }*/
}

function _dosomething_wf_modify_webform_component_mapping($node) {
  $mapping = array();
  $components = $node->webform['components'];
  foreach ($components as $i => $component) {
    $key = $component['form_key'];
    $mapping[$key] = $i;
  }
  return $mapping;
}

function dosomething_wf_modify_webform_select_options_info() {
    $items = array();
    $items['user_clubs'] = array(
        'title' => t('User\'s clubs'),
        'options callback' => 'dosomething_wf_modify_options_user_clubs'
    );
    return $items;
}

function dosomething_wf_modify_options_user_clubs() {
    global $user;
    $q = "SELECT n.nid, n.title FROM {og_uid} og JOIN {node} n ON og.nid=n.nid WHERE n.type='club' AND og.uid='{$user->uid}' AND og.is_active=1";
    $rs = db_query($q);
    
    $options = array();
    while ($club = db_fetch_array($rs)) {
        $options[$club['nid']] = $club['title'];
    }
    
    if (count($options) === 0)
        $options[0] = '< Please create a club. >';
    return $options;
}


