<?

function dosomething_views_views_pre_execute(&$view) {
  if ($view->name == 'scavenger_signups' && $view->current_display == 'block_1') {
    $search = 'ORDER BY';
    $replace = 'GROUP BY title,postal_code ORDER BY';
    $view->build_info['query'] = str_replace($search,$replace,$view->build_info['query']);
    $view->build_info['count_query'] = str_replace($search,$replace,$view->build_info['count_query']);
  }
}

function dosomething_views_views_post_render(&$view, &$output, &$cache) {
  if ($view->name == 'thanks_911_signups' && $view->current_display == 'paged_feed_1') {
    $output = json_encode((array) simplexml_load_string($output));
  }
}


?>
