<?

function ds_signup_block($op = 'list', $delta = 0, $edit = array()) {
  $blocks = array();

  if ($op == 'list') {
    $blocks[0]['info'] = 'Signup top right';
    $blocks[0]['cache'] = BLOCK_NO_CACHE;
  } else if ($op == 'view') {
    switch ($delta) {
      case 0:
        $blocks['subject'] = '';
        $blocks['content'] = _ds_signup_block();
        break;
    }
  }

  return $blocks;
}
	

function _ds_signup_block() {
  global $user;
  $block_str = '<div id="sign-up">
    <a href="/news/were-getting-makeover-not-plastic-surgery" style="color: magenta; font-size: 16px; font-weight: bold;">New site coming soon!</a>';
  $block_str .= '<div class="blue" style="margin-top: 10px;">'.
    '<img class="need-help" src="/sites/all/themes/dosomething/images/need-help.png"/>'.
    '<p><span class="lightblue">Text </span> HELPME to 38383</p>'.
    '<p><span class="lightblue"><a href="mailto:helpme@dosomething.org">Email</a> </span> helpme@dosomething.org</p>'.
	'<p>Sign up to our newsletter!</p>'.
    '<form method="POST" action="http://www.dosomething.org/nd/infusionsoft/webform.php">'.
    '<input type="text" id="email" name="Email" value="email" maxlength="" class="short" onClick="if (this.value == this.defaultValue) { this.value=\'\'; }" onBlur="if (this.value == \'\') { this.value=this.defaultValue; }" />'.
    '<input type="submit" name="go" value="Go" alt="go" class="submit" /></form>'.
   '<iframe src="http://www.facebook.com/plugins/like.php?href=facebook.com%2Fdosomething&amp;send=false&amp;layout=button_count&amp;width=85&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:85px; height:21px;" allowTransparency="true"></iframe> &nbsp;'.
    '</div>';
  if ($user->uid) {
    $block_str .= l('My Account', 'user/' . $user->uid).' | <a href="/logout">Log Out</a>';
  } else {
    $redirect = array( 'html' => true, 'query' => drupal_get_destination());
    $block_str .= l('Log In','user/login',$redirect).
      ' | '.l('Join Us','user/register');
  }

  $block_str .= '</div>';
  return $block_str;
}


?>
